### ISSUE TITLE
Desktop icons like Openbox had with `pcmanfm --desktop` or `idesk`? (could use layer shell)

### ISSUE THREAD

**Issue by xplshn** [wizbright/waybox#40]
Hi, I am looking for a wayland WM that I can turn into a more desktop-like experience for others to use. Like Puppy Linux has done with JWM. My current implementation of something like `idesk` but for Wayland is very barebones, and it isn't any good. But hopefully it can be a starting point if you decide to overtake the project or add support for this within waybox itself.

https://github.com/xplshn/wayland-imd/tree/master/i2ywm

Thanks!

**Comment by keithbowes** [comment]
Yeah, way back, I considered implementing a desktop system, but I do think it's better to use external tools whenever possible (don't reinvent the wheel unless you have a better wheel). You can use things like cairo-dock and lavalauncher to provide some icons, but perhaps not enough if you need a lot of icons on your desktop. I never used idesk with Openbox, so I don't know, but my understanding was that it was fairly laborious to configure, since it didn't use the standard ~/Desktop/*.desktop files.

wlr-layer-shell works well in Waybox, as far as I know (Waybar, lavalauncher, and rofi-wayland work fine at least). It should work, since I took the code from Sway way back; I haven't kept it updated to the latest Sway code, though. One thing that doesn't work though is wlr-foreign-toplevel-management, so you have to manually specify the margins in rc.xml. I added support for ext-foreign-toplevel-list a while back (so [lswt](https://git.sr.ht/~leon_plickat/lswt/) works but things like Waybar and rofi use the proprietary protocol to list open windows, so their listing of open windows aren't working yet; I consider it to be their problem for not using the standard protocol), but the other parts of wlr-foreign-toplevel-management haven't been standardized yet.

**Comment by xplshn** [comment]
I am suggesting what could be a new component, there's no existing way to get desktop icons (as in, desktop, not a dock) in Wayland AFAIK

**Comment by Narrat** [comment]
> I am suggesting what could be a new component, there's no existing way to get desktop icons (as in, desktop, not a dock) in Wayland AFAIK

IIRC the people over at Raspberry Pi Desktop are working on `pcmanfm --desktop` + a wayland compositor.
Dunno if `nautilus` or `nemo` have retained their `--desktop` option. But there seem to be ways.
